
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/networkpatterns2/secrets/database-password/versions/latest"
        path: "database-password"
      - resourceName: "projects/networkpatterns2/secrets/api-key/versions/latest"  
        path: "api-key"
      - resourceName: "projects/networkpatterns2/secrets/jwt-secret/versions/latest"
        path: "jwt-secret"