apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-podman-pod
  labels:
    app: podman-runner
spec:
  serviceAccountName: secret-access-sa
  containers:
  - name: podman-runner
    image: us-central1-docker.pkg.dev/networkpatterns2/gke-images/podman-runner:latest
    securityContext:
      privileged: true
      runAsUser: 0
      capabilities:
        add:
        - SYS_ADMIN
        - DAC_OVERRIDE
        - CHOWN
        - FOWNER
        - SETUID
        - SETGID
    volumeMounts:
    - name: database-password
      mountPath: /mnt/secrets
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1"
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
  volumes:
  - name: database-password
    csi:
      driver: secrets-store-gke.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: gcp-secret-provider
  restartPolicy: Always